import {MeshoptDecoder} from '../dist/vendor/libs/meshopt_decoder.module.js';
import fs from 'node:fs';
import assert from 'node:assert/strict';
import * as T from 'three';
import {GLTFLoader} from '../dist/vendor/loaders/GLTFLoader.js';
import {CharacterMotion} from '../dist/character-motion.js';
import {CharacterPicker} from '../dist/character-picker.js';
import {TailGrounding} from '../dist/tail-grounding.js';
globalThis.self=globalThis;globalThis.createImageBitmap=async()=>({width:2048,height:2048,close(){}});
const b=fs.readFileSync('dist/assets/models/beluga.glb');
const gltf=await new GLTFLoader().setMeshoptDecoder(MeshoptDecoder).parseAsync(b.buffer.slice(b.byteOffset,b.byteOffset+b.byteLength),'');
const c=gltf.scene,m=new CharacterMotion(c,gltf.animations,{random:()=>.43}),g=new TailGrounding(c),picker=new CharacterPicker(c);
const bones=[];c.traverse(o=>{if(o.isBone)bones.push(o);if(o.isMesh)o.raycast=()=>{throw new Error('Detailed mesh raycast must never run on tap')}});
const tick=(n=1,dt=1/60)=>{for(let i=0;i<n;i++){m.update(dt);g.update(m);for(const b of bones){assert(b.position.toArray().every(Number.isFinite));assert(Math.abs(b.quaternion.length()-1)<.00001, b.name+' q='+b.quaternion.length()+' action='+m.current?.type+' gentle='+m.gentle);}assert(g.lift<.23);}};
tick(180);
assert(g.contacts[0].distanceTo(g.contacts[1])>.20,'Relaxed should retain a natural supporting stance');
assert(Math.abs(g.contacts[0].z-g.contacts[1].z)>.015,'The tucked fluke needs gentle front/back separation');
assert(Math.abs(Math.min(...g.contacts.map(p=>p.y)))<.00001,'Crossed fins must stay on the floor');
for(const clip of m.clips.values())assert.equal(new Set(clip.tracks.map(t=>t.name)).size,clip.tracks.length,'Animation bindings must be unique: '+clip.name);
const crossed=g.contacts.map(p=>p.clone());tick(100,0);g.contacts.forEach((p,i)=>assert(p.distanceTo(crossed[i])<.00001,'Paused relaxed pose must not drift'));
const resting=c.getObjectByName('ArmR').quaternion.clone();
m.setPose('little');tick(240);assert(resting.angleTo(c.getObjectByName('ArmR').quaternion)>.28,'Little pose must visibly raise the free flipper');
const littleDirection=()=>c.getObjectByName('FinR').getWorldPosition(new T.Vector3()).sub(c.getObjectByName('ArmR').getWorldPosition(new T.Vector3())).normalize();
const little= littleDirection();
m.setPose('tada');tick(240);assert(little.angleTo(littleDirection())>.65,'Little and Ta-da need distinct visible flipper directions');
c.userData.carryingTote=true;m.setPose('little');tick(240);const carriedLittle=littleDirection();m.setPose('tada');tick(240);assert(carriedLittle.angleTo(littleDirection())>.65,'The tote must not suppress the expressive free flipper');
c.userData.carryingTote=false;m.setPose('little');
tick(900);assert.equal(m.selectedPose,'little');assert(m.poseLayers[0].action.getEffectiveWeight()>.99);
m.play('boop');tick(240);assert.equal(m.current,null);assert.equal(m.layers.length,0);assert(m.poseLayers[0].action.getEffectiveWeight()>.99,'Return to selected pose after nose tap');
const idleTime=m.idle.time;tick(120);assert.notEqual(m.idle.time,idleTime,'Idle keeps running');
for(const carried of [false,true])for(const gentle of [false,true]){
 c.userData.carryingTote=carried;m.setGentle(gentle);
 for(const action of ['wave','kiss','wiggle','twirl','boop','pose','dress','dance','love','camera']){m.play(action);tick(80);m.play('boop');tick(18);m.play(action);tick(420);assert.equal(m.current,null);assert.equal(m.layers.length,0);}
 m.setPose('tada');tick(150);const held=bones.map(b=>({q:b.quaternion.clone(),p:b.position.clone()}));
 tick(100,0);bones.forEach((b,i)=>{assert(b.position.distanceTo(held[i].p)<.00001,'No accumulated grounding: '+b.name);assert(b.quaternion.clone().normalize().angleTo(held[i].q.clone().normalize())<.00001,'No accumulated pose: '+b.name);});
}
const reactions=Array.from({length:20},()=>{m.play('dress');const type=m.current.type;tick(300);return type});
for(let i=0;i<20;i+=4)assert.equal(new Set(reactions.slice(i,i+4)).size,4);
for(let i=1;i<20;i++)assert.notEqual(reactions[i],reactions[i-1]);
m.setGentle(false);m.setPose('relaxed');c.userData.carryingTote=false;tick(180);
const camera=new T.PerspectiveCamera(35,1,.1,100);camera.position.set(0,2.1,8);camera.lookAt(0,2.1,0);camera.updateMatrixWorld(true);
const head=c.getObjectByName('Head').getWorldPosition(new T.Vector3());head.y+=.24;head.z+=.5;
const headNdc=head.clone().project(camera);assert.equal(picker.pick(headNdc,camera),'boop');assert.equal(picker.pick(new T.Vector2(.99,.99),camera),null);
const start=performance.now();for(let i=0;i<1000;i++)picker.pick(headNdc,camera);const pickMs=performance.now()-start;assert(pickMs<2000,'Tap picking too slow');
console.log(JSON.stringify({status:'PASS',poses:'Held / blend back after actions',reactions:new Set(reactions).size,repeatedInterruptedActions:40,pausedFrames:500,analyticPicks:1000,pickMs:Math.round(pickMs)},null,2));
